### ISSUE TITLE
Problem when swiping card down

### ISSUE THREAD

**Issue by MrPikokon-creator** [3DJakob/react-tinder-card#117]
After the latest update 1.6.0 there was a problem. It doesn't exist in older versions.
When you swipe the card downon android, the page starts to update.

**Comment by 3DJakob** [comment]
On android in the browser or on native? Also what do you mean by update?

**Comment by MrPikokon-creator** [comment]
https://user-images.githubusercontent.com/63126813/196038373-70a2a175-aca1-42f1-8f99-77e7cf75164d.mp4

**Comment by MrPikokon-creator** [comment]
This is 1.6.0
Perhaps the problem is somehow related to the library @react-spring/web, which needed to be connected after updating to 1.6.0.

**Comment by 3DJakob** [comment]
Aha, I think I know why. If you give your green card the className 'card' it will work I think. I will try to solve this in a better way. The problem is that before there was a prevent default on everything preventing you from scrolling. Now it is only on the card I will look into a better way of solving this.

**Comment by 3DJakob** [comment]
Could you verify if the problem is present at http://3djakob.github.io/react-tinder-card-demo/

**Comment by MrPikokon-creator** [comment]
Demo is ok

**Comment by 3DJakob** [comment]
In version 1.6.1 this is now working per default and if you want to be able to press an element you simply add the className `pressable` to that element.
