### ISSUE TITLE
Double animation when aborting swipe

### ISSUE THREAD

**Issue by ammyt** [3DJakob/react-tinder-card#19]
Hi, many thanks for this component!

One issue that I have found is when you move an element but return it back, this "swipe back to place animation" happens twice. It looks counterintuitive.

I tried to look into sources to figure out what's happening to no avail. Any tips?

**Comment by ammyt** [comment]
Fixed by reducing timeout in animateBack, althought I don't know how exactly it works.
```
setTimeout(() => {
    element.style.transform = 'none'
  }, settings.snapBackDuration * **0.1**)
```

**Comment by ammyt** [comment]
There is also a bad delay caused when moving an element but releasing, calling animateback(). Doing that multiple times with the same element causes lagging. Overall the behavior is now much better by removing both Timeouts and adding 
```
  element.style.transform = 'none'
  element.style.transition = '0ms'
```
instead, but again I don't know if this causes other things to break!

**Comment by 3DJakob** [comment]
Hey! Glad you like to module. That is very strange I haven't had that issue 🤔 However there are some problems with multiple re-renders which could be causing issues here. Unfortunately, I don't have time right now to take a look at this but perhaps if your solution helps you could do a pr. Also posting a simple demo repo to show the issue would help me a lot. Or maybe this issue is present on my demo repo?

**Comment by 3DJakob** [comment]
Since this issue is not present on the demo repository and the fact that the code in question has since changed in future releases I am closing this issue. If anyone experiences this again feel free to reopen.
