### ISSUE TITLE
onCardLeftScreen={} event not triggering setstate hook or any funtions just console logs?

### ISSUE THREAD

**Issue by UPLukeet** [3DJakob/react-tinder-card#21]
For some reason the onSwipe={} and onCardLeftScreen={} cannot update state or for whatever reason do not currently is this a known issue is there a fix? I was trying to cycle through array data using a queue and the shift() and push() functions but for some unknown reason, it wouldn't work. I just tested my code using the onclick={} event handler on a button and the code works perfectly the data is cycled through correctly.
 (for simplicity I am only posting the lines of code that are relevant)

```
import React, { useState, useEffect } from 'react';
import Data from '../Data/webApps_data';
import TinderCard from 'react-tinder-card';

function Webapps() {

//sets initial cards within the queue
    let [cardQueue, setCardQueue] = useState([Data[0], Data[1], Data[2]]);

    //sets the index of card that will be pushed into queue
    const [cardQueueLength, setCardQueueLength] = useState(3);

 const onCardLeftScreen = () => {
        //removes card from front of queue
        cardQueue.shift();
        //iterates through cards(sets up loop)
        setCardQueueLength(cardQueueLength < Data.length - 1 ? cardQueueLength + 1 : 0 );
        //pushes a card to back of queue
        cardQueue.push(Data[cardQueueLength]);
        //console logs cards in arrays and the index of the card being pushed to back of queue
        console.log(cardQueue);
        console.log(cardQueueLength);
    }

return (
{cardQueue.map((Projects, index) => {
                    return <TinderCard key={Projects.workName} preventSwipe={['up', 'down']} onSwipe={onCardLeftScreen} className='Cards'>
)
}
```
This exact function works perfectly so there's either an issue with my code implementation or the library cheers

**Comment by UPLukeet** [comment]
Can I just add other than this issue the module seems to work great would be good if I could get an answer to this then my projects finished ahahaha otherwise will need to hunt for a new libary

**Comment by UPLukeet** [comment]
was worried my example wasn't clear enough so I built a code sandbox with something very similar to my project to display the issue, I've added a button which runs the function correctly can anyone see the issue? **[Sandbox](https://codesandbox.io/s/sleepy-sunset-jqjst?file=/src/styles.scss)**

**Comment by 3DJakob** [comment]
Hey! I am pretty sure that the problem is not with my library but with updating your state. You should never mutate state directly meaning doing stuff like `cardQueue.shift()`. What happens is that react is not aware of the change and won't re-render. To solve this use the `setCardQueueLength` function. Like this `setCardQueueLength(cardQueue.shift())` I hope that solves your issue.

**Comment by UPLukeet** [comment]
> Hey! I am pretty sure that the problem is not with my library but with updating your state. You should never mutate state directly meaning doing stuff like `cardQueue.shift()`. What happens is that react is not aware of the change and won't re-render. To solve this use the `setCardQueueLength` function. Like this `setCardQueueLength(cardQueue.shift())` I hope that solves your issue.
> 
> To debug this better I suggest printing out your cardQueue variable on render like this to make sure it updates.
> `<p>{JSON.stringify(cardQueue)}</p>`

Hi mate thanks for the replies, since posting this I have fixed the state mutation issue like so:
```
 const CardLeftScreen = () => {

        const dataIndex = cardQueueLength < Data.length - 1 ? cardQueueLength + 1 : 0;

        //accesses queue without mutating state
        const newCardQueue = [...cardQueue];

        //pushes a card to back of queue
        newCardQueue.push(Data[dataIndex]);

        //removes card from front of queue
        newCardQueue.shift();

        //updates state
        setCardQueueLength(dataIndex)
        setCardQueue(newCardQueue)
        
        //sets slideshow to true
        setSlideShow(true)

        //console logs cards in arrays and the index of the card being pushed to back of queue
        console.log(cardQueue);
        console.log(cardQueueLength);
    }
```
but the issue still persists, I will try your fix and debugging solution though thank you!

**Comment by UPLukeet** [comment]
@3DJakob I've updated my sandbox to reflect the changes suggested but its still not working take a look [**here**](https://codesandbox.io/s/sleepy-sunset-jqjst?file=/src/styles.scss), hopefully we can work out the issue can you not replicate it? its the same for my actual project and the sandbox

**Comment by 3DJakob** [comment]
Hi! Now it looks better. How do you know that the issue still persist? 

Because your console logs at the end will log the old state! This is because the state does not get updated until the the function has finished to prevent unnecessary multiple reloads.

Try logging like I mentioned with JSON.stringify, logging in the function body or using the useEffect hook.

Hope that helps!

**Comment by 3DJakob** [comment]
I don’t really have time right now to find the problem in your code sandbox however if you only run setCardQueue([]); on CardLeftScreen you will see how all the cards disappear. So it is definitely your state that either doesn’t get updated or gets updated but to its original state. Hope that help you find the problem!

**Comment by UPLukeet** [comment]
@3DJakob completely understand if you do get a chance let me know if you find anything and yes it runs only once if you swipe a card away in the sandbox the first card is actually shifted out fo the array but it doesn't run again. I also put a button in the top right with an onClick to help debug and it runs completely as intended just the onCardLeftScreen doesn't?

**Comment by 3DJakob** [comment]
I experimented a bit with your sample as it intrigued me. The problem is that you have duplicate keys in your data structure. I solved it using key={Projects.workName + Math.random()} . The problem is that react doesn’t know that it needs to render new items as it cannot distinguish them from the old ones. You should use a module like UUID to add unique ids to your dataset.

Have a nice evening and good luck with your project!

**Comment by UPLukeet** [comment]
@3DJakob Wow thank you sooo much! I guess the onClick worked because it forced react to update the dom cheers mate!

**Comment by UPLukeet** [comment]
@3DJakob Hi sorry to bother you again but your solution is causing the all the cards to be rerendered upon any actions, I don't understand why the keys I was using prior weren't sufficient they were all unique from there siblings?

**Comment by UPLukeet** [comment]
https://stackoverflow.com/questions/29808636/when-giving-unique-keys-to-components-is-it-okay-to-use-math-random-for-gener

**Comment by 3DJakob** [comment]
Yes I see. This is because when we modify the state react starts a new render. And when it does that it will map though the objects again assigning new math.random keys to your data which the will cause it to think that all cards have been replaced triggering an actual reload of all elements.

To solve this ju must add unique keys to all items in your actual data structure. Preferable in the data itself but if you can’t do that the just create a new data const using map on the input data and add a unique key.
Like this:

import Data from "./webApps_data";
import { v4 as uuidv4 } from 'uuid';
const newData = Data.map(obj => {…obj, id: uuidv4()})

An alternative solution is to make the key a combination of different properties so that they all will be unique. Though I would not recommend this solution as it is ugly.

Also using the index as key is in your case a bad solution as the index will change if you remove or add things to the array then causing all elements to re-render.

Hope this solves your issues.
