### ISSUE TITLE
Error occurred when I click near of the card's border. (In mobile)

### ISSUE THREAD

**Issue by LautaroCesso** [3DJakob/react-tinder-card#38]
Hi, many thanks for this component!

https://user-images.githubusercontent.com/59095036/108387291-375d1600-71ec-11eb-92dd-68b2bcd767b6.mp4

This error occurred when I click near of the card's border. (In mobile)

![image](https://user-images.githubusercontent.com/59095036/108387931-dd108500-71ec-11eb-8818-afb8b0ed8aef.png)

[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

![image](https://user-images.githubusercontent.com/59095036/108388103-0f21e700-71ed-11eb-8498-912367aa55eb.png)

The pictures and video are from the demo page

I have the same error in my local proyect.

Sorry for my English.

**Comment by cw-vishalyadav** [comment]
This issue can be fixed by using `if (ev.cancelable) ev.preventDefault();` instead of `ev.preventDefault()` in toushstart event listener.
I have referred to [this](https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/) article for information.

**Comment by 3DJakob** [comment]
This fix has been implemented in https://github.com/3DJakob/react-tinder-card/pull/116 and released in 1.6.0 🎉
