### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by schmem55** [3DJakob/react-tinder-card#42]
Hi
Great projects very useful!
Is there any option to make the swiper infinite ( when you swipe a card then it comes back to the bottom of the queue) ?
thanks

**Comment by saurabhsahmsft** [comment]
+1 or can you add an option for undo

**Comment by 3DJakob** [comment]
Hello @schmem55, this is totally up to the user using the module to implement. Since the module itself is only a single card you can code around it to add new cards to the stack on the `onCardLeftScreen` event.  If you have a state with the cards to be rendered just pop and push to that on the event and you should get it working!

**Comment by 3DJakob** [comment]
> +1 or can you add an option for undo

This is a highly requested feature and might be added in the future! PRs for this are welcome!

**Comment by shamoons** [comment]
Would love a loop feature
