### ISSUE TITLE
Inputs inside TinderCard do not work

### ISSUE THREAD

**Issue by usama-mk** [3DJakob/react-tinder-card#62]
Inputs inside tinder Cards do not work they are not accessible

**Comment by 3DJakob** [comment]
First of I'm assuming this issue is on mobile using the none native version. This is because the cards use event listeners for moving them around. This issue is very related to this https://github.com/3DJakob/react-tinder-card/issues/55. The solution is very similar to the one in that thread. Try adding a `onTouchEnd` event on your input and in that event use a ref to your input and run `.focus()`. That will make your cursor appear in the input field and you should be able to type as normal. Hope this helps!
