### ISSUE TITLE
swipe does not work android react-native

### ISSUE THREAD

**Issue by hoseinfo** [3DJakob/react-tinder-card#63]
hi 
swipe does not work on android?
does anybody resolve it?
(my code same as your simple example )

**Comment by 3DJakob** [comment]
Are you using react-native or regular react?

**Comment by Yassinelaadraoui** [comment]
am facing the same issue, swiping is working but freezes when i set position to absolute

**Comment by 3DJakob** [comment]
@Yassinelaadraoui Could you please verify that this is an issue in the demo repository as well?

Try cloning the demo repo https://github.com/3DJakob/react-native-tinder-card-demo
Run npm install followed by npm start to run the demo in expo.

If the problem persists there I could take a look at it. Otherwise, just look at that code and try to understand how it's made.

**Comment by trung-mta** [comment]
Facing problem too, IOS working fine but android cannot swipe, remove absoute make it work but image not layering
