### ISSUE TITLE
OnTouchEnd no solution button click inside card

### ISSUE THREAD

**Issue by Airrudi** [3DJakob/react-tinder-card#76]
I have a button inside the TinderCard, OnClick does not work. I read in previous issues that OnTouchEnd can be used. However, when I click and hold the button and drag the card away, releasing the card will trigger the button click anyway.

In my scenario I want the click action only when it's a simple click, no longer after I started dragging the card.

Using OnTouchStart gives me another error, since my button action is navigating to another page. It complaints it cannot find some card elements on the new page:

_Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at getTranslate (index.js:113)
    at index.js:178
    at HTMLDivElement.<anonymous> (index.js:258)_

What can I do?

Thnx

**Comment by 3DJakob** [comment]
The behavior you want is not really something related to the tinder card per se. Normally when clicking a button holding the mouse down and then releasing will trigger the press. Because the card moves with your mouse this behavior happens. What you need to do is somehow once you have moved the card over a certain threshold disable the button press. This could probably be implemented using the `useRef()` hook. Then checking the translation changes of the card. 

Another solution would be setting a delay on the onRelease event and then checking if `onSwipe` gets called within something like 10ms and in that case ignoring the button press.

**Comment by Airrudi** [comment]
Thanks @3DJakob , I'll give this a go
