### ISSUE TITLE
Swipe Does not work on Android or Emulator..

### ISSUE THREAD

**Issue by anthonycoded** [3DJakob/react-tinder-card#77]
I downloaded the demo repository and ran it. The buttons work but no ability to swipe. Works on my iphone. Some of the dependencies are outdated,  not sure if thats the cause of the issue. I have "react-spring": "^8.0.27" installed.

**Comment by functioncall** [comment]
Same here.

**Comment by 3DJakob** [comment]
@anthonycoded @functioncall  Strange! Is this using react-native or react? I'll try to take a look at it as soon as possible.

**Comment by chloeward00** [comment]
when i put className="Swipe", my images disappear when using TMDB api, do you know how i could fix this?

**Comment by chocowhiskey** [comment]
Any news? Been having the same problem on the emulator, but on iOS simulator works perfectly fine.. :(

**Comment by 3DJakob** [comment]
@chloeward00 @chocowhiskey @functioncall Can somebody clarify if this is the native module or the web module? 

I have tested running both [react-tinder-card-demo](https://github.com/3DJakob/react-tinder-card-demo) and [react-native-tinder-card-demo](https://github.com/3DJakob/react-native-tinder-card-demo) on an android device without any issues. This could simply have been fixed with another patch or it is something device-specific. I'm closing this for now but if anyone still has this issue feel free to reopen it.
